import { MigrateDownArgs, MigrateUpArgs, sql } from '@payloadcms/db-sqlite'

const upStatements = [
  "CREATE TABLE IF NOT EXISTS `_home_v` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`version_title` text DEFAULT 'Главная',\n\t`version_hero_type` text DEFAULT 'lowImpact',\n\t`version_hero_rich_text` text,\n\t`version_hero_media_id` integer,\n\t`version_meta_title` text,\n\t`version_meta_image_id` integer,\n\t`version_meta_description` text,\n\t`version__status` text DEFAULT 'draft',\n\t`version_updated_at` text,\n\t`version_created_at` text,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`latest` integer,\n\t`autosave` integer,\n\tFOREIGN KEY (`version_hero_media_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`version_meta_image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_about_company` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_path` text NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`hero_eyebrow` text,\n\t`hero_title` text,\n\t`hero_primary_button_label` text,\n\t`hero_primary_button_url` text,\n\t`hero_secondary_button_label` text,\n\t`hero_secondary_button_url` text,\n\t`hero_hero_image_id` integer,\n\t`partners_heading` text,\n\t`partners_button_label` text,\n\t`partners_button_url` text,\n\t`final_heading` text,\n\t`final_button_label` text,\n\t`final_button_url` text,\n\t`_uuid` text,\n\t`block_name` text,\n\tFOREIGN KEY (`hero_hero_image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_about_company_facts` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`title` text,\n\t`description` text,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v_blocks_about_company`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_about_company_final_paragraphs` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`text` text,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v_blocks_about_company`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_about_company_hero_paragraphs` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`text` text,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v_blocks_about_company`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_about_company_hero_visual_tags` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`label` text,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v_blocks_about_company`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_about_company_partners_paragraphs` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`text` text,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v_blocks_about_company`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_about_company_partners_points` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`label` text,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v_blocks_about_company`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_about_company_sections` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`heading` text,\n\t`surface_style` integer DEFAULT false,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v_blocks_about_company`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_about_company_sections_paragraphs` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`text` text,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v_blocks_about_company_sections`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_archive` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_path` text NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`intro_content` text,\n\t`populate_by` text DEFAULT 'collection',\n\t`relation_to` text DEFAULT 'products',\n\t`limit` numeric DEFAULT 10,\n\t`_uuid` text,\n\t`block_name` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_banner` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_path` text NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`style` text DEFAULT 'info',\n\t`content` text,\n\t`_uuid` text,\n\t`block_name` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_carousel` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_path` text NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`populate_by` text DEFAULT 'collection',\n\t`relation_to` text DEFAULT 'products',\n\t`limit` numeric DEFAULT 10,\n\t`populated_docs_total` numeric,\n\t`_uuid` text,\n\t`block_name` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_contacts_hub` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_path` text NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`hero_eyebrow` text,\n\t`hero_title` text,\n\t`hero_description` text,\n\t`hero_button_label` text,\n\t`hero_button_url` text,\n\t`hero_contacts_phone_label` text,\n\t`hero_contacts_phone` text,\n\t`hero_contacts_email_label` text,\n\t`hero_contacts_email` text,\n\t`main_contacts_heading` text,\n\t`main_contacts_description` text,\n\t`main_contacts_phone_label` text,\n\t`main_contacts_phone` text,\n\t`main_contacts_email_label` text,\n\t`main_contacts_email` text,\n\t`requisites_heading` text,\n\t`requisites_name_label` text,\n\t`requisites_name` text,\n\t`requisites_inn_label` text,\n\t`requisites_inn` text,\n\t`requisites_ogrn_label` text,\n\t`requisites_ogrn` text,\n\t`requisites_email_label` text,\n\t`requisites_email` text,\n\t`requisites_phone_label` text,\n\t`requisites_phone` text,\n\t`form_heading` text,\n\t`form_description` text,\n\t`form_button_label` text,\n\t`final_heading` text,\n\t`final_description` text,\n\t`final_button_label` text,\n\t`final_button_url` text,\n\t`_uuid` text,\n\t`block_name` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_contacts_hub_directions` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`title` text,\n\t`description` text,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v_blocks_contacts_hub`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_content` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_path` text NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`_uuid` text,\n\t`block_name` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_content_columns` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`size` text DEFAULT 'oneThird',\n\t`rich_text` text,\n\t`enable_link` integer,\n\t`link_type` text DEFAULT 'reference',\n\t`link_new_tab` integer,\n\t`link_url` text,\n\t`link_label` text,\n\t`link_appearance` text DEFAULT 'default',\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v_blocks_content`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_cta` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_path` text NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`rich_text` text,\n\t`_uuid` text,\n\t`block_name` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_cta_links` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`link_type` text DEFAULT 'reference',\n\t`link_new_tab` integer,\n\t`link_url` text,\n\t`link_label` text,\n\t`link_appearance` text DEFAULT 'default',\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v_blocks_cta`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_form_block` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_path` text NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`form_id` integer,\n\t`enable_intro` integer,\n\t`intro_content` text,\n\t`_uuid` text,\n\t`block_name` text,\n\tFOREIGN KEY (`form_id`) REFERENCES `forms`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_home_b2_b` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_path` text NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`eyebrow` text DEFAULT 'B2B / ГОСЗАКУПКИ / ПАРТНЕРСТВО',\n\t`title` text DEFAULT 'Поставки под проект, закупку и дилерские задачи',\n\t`description` text DEFAULT 'Помогаем пройти путь от запроса до поставки: уточняем задачу, подбираем оборудование, готовим коммерческое предложение и сопровождаем закупку.',\n\t`button_label` text DEFAULT 'Обсудить задачу и получить КП',\n\t`button_url` text DEFAULT '/kontakty',\n\t`_uuid` text,\n\t`block_name` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_home_b2_b_points` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`title` text,\n\t`description` text,\n\t`icon` text DEFAULT 'tender',\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v_blocks_home_b2_b`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_media_block` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_path` text NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`media_id` integer,\n\t`_uuid` text,\n\t`block_name` text,\n\tFOREIGN KEY (`media_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_service_center` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_path` text NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`hero_eyebrow` text,\n\t`hero_title` text,\n\t`hero_button_label` text,\n\t`hero_button_url` text,\n\t`hero_hero_image_id` integer,\n\t`service_request_heading` text,\n\t`service_request_description` text,\n\t`final_heading` text,\n\t`final_description` text,\n\t`final_button_label` text,\n\t`final_button_url` text,\n\t`_uuid` text,\n\t`block_name` text,\n\tFOREIGN KEY (`hero_hero_image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_service_center_cards` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`title` text,\n\t`description` text,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v_blocks_service_center`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_service_center_hero_paragraphs` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`text` text,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v_blocks_service_center`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_service_center_hero_visual_tags` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`label` text,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v_blocks_service_center`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_service_center_sections` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`heading` text,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v_blocks_service_center`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_service_center_sections_paragraphs` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`text` text,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v_blocks_service_center_sections`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_service_center_service_request_steps` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`label` text,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v_blocks_service_center`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_blocks_three_item_grid` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_path` text NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`_uuid` text,\n\t`block_name` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_rels` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`order` integer,\n\t`parent_id` integer NOT NULL,\n\t`path` text NOT NULL,\n\t`pages_id` integer,\n\t`categories_id` integer,\n\t`products_id` integer,\n\tFOREIGN KEY (`parent_id`) REFERENCES `_home_v`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`pages_id`) REFERENCES `pages`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`categories_id`) REFERENCES `categories`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`products_id`) REFERENCES `products`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_home_v_version_hero_links` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`link_type` text DEFAULT 'reference',\n\t`link_new_tab` integer,\n\t`link_url` text,\n\t`link_label` text,\n\t`link_appearance` text DEFAULT 'default',\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_home_v`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_pages_v_blocks_home_b2_b` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_path` text NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`eyebrow` text DEFAULT 'B2B / ГОСЗАКУПКИ / ПАРТНЕРСТВО',\n\t`title` text DEFAULT 'Поставки под проект, закупку и дилерские задачи',\n\t`description` text DEFAULT 'Помогаем пройти путь от запроса до поставки: уточняем задачу, подбираем оборудование, готовим коммерческое предложение и сопровождаем закупку.',\n\t`button_label` text DEFAULT 'Обсудить задачу и получить КП',\n\t`button_url` text DEFAULT '/kontakty',\n\t`_uuid` text,\n\t`block_name` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_pages_v`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `_pages_v_blocks_home_b2_b_points` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`title` text,\n\t`description` text,\n\t`icon` text DEFAULT 'tender',\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_pages_v_blocks_home_b2_b`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`title` text DEFAULT 'Главная',\n\t`hero_type` text DEFAULT 'lowImpact',\n\t`hero_rich_text` text,\n\t`hero_media_id` integer,\n\t`meta_title` text,\n\t`meta_image_id` integer,\n\t`meta_description` text,\n\t`_status` text DEFAULT 'draft',\n\t`updated_at` text,\n\t`created_at` text,\n\tFOREIGN KEY (`hero_media_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`meta_image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_about_company` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_path` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`hero_eyebrow` text,\n\t`hero_title` text,\n\t`hero_primary_button_label` text,\n\t`hero_primary_button_url` text,\n\t`hero_secondary_button_label` text,\n\t`hero_secondary_button_url` text,\n\t`hero_hero_image_id` integer,\n\t`partners_heading` text,\n\t`partners_button_label` text,\n\t`partners_button_url` text,\n\t`final_heading` text,\n\t`final_button_label` text,\n\t`final_button_url` text,\n\t`block_name` text,\n\tFOREIGN KEY (`hero_hero_image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_about_company_facts` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`title` text,\n\t`description` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home_blocks_about_company`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_about_company_final_paragraphs` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`text` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home_blocks_about_company`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_about_company_hero_paragraphs` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`text` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home_blocks_about_company`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_about_company_hero_visual_tags` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`label` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home_blocks_about_company`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_about_company_partners_paragraphs` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`text` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home_blocks_about_company`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_about_company_partners_points` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`label` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home_blocks_about_company`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_about_company_sections` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`heading` text,\n\t`surface_style` integer DEFAULT false,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home_blocks_about_company`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_about_company_sections_paragraphs` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`text` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home_blocks_about_company_sections`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_archive` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_path` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`intro_content` text,\n\t`populate_by` text DEFAULT 'collection',\n\t`relation_to` text DEFAULT 'products',\n\t`limit` numeric DEFAULT 10,\n\t`block_name` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_banner` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_path` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`style` text DEFAULT 'info',\n\t`content` text,\n\t`block_name` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_carousel` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_path` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`populate_by` text DEFAULT 'collection',\n\t`relation_to` text DEFAULT 'products',\n\t`limit` numeric DEFAULT 10,\n\t`populated_docs_total` numeric,\n\t`block_name` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_contacts_hub` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_path` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`hero_eyebrow` text,\n\t`hero_title` text,\n\t`hero_description` text,\n\t`hero_button_label` text,\n\t`hero_button_url` text,\n\t`hero_contacts_phone_label` text,\n\t`hero_contacts_phone` text,\n\t`hero_contacts_email_label` text,\n\t`hero_contacts_email` text,\n\t`main_contacts_heading` text,\n\t`main_contacts_description` text,\n\t`main_contacts_phone_label` text,\n\t`main_contacts_phone` text,\n\t`main_contacts_email_label` text,\n\t`main_contacts_email` text,\n\t`requisites_heading` text,\n\t`requisites_name_label` text,\n\t`requisites_name` text,\n\t`requisites_inn_label` text,\n\t`requisites_inn` text,\n\t`requisites_ogrn_label` text,\n\t`requisites_ogrn` text,\n\t`requisites_email_label` text,\n\t`requisites_email` text,\n\t`requisites_phone_label` text,\n\t`requisites_phone` text,\n\t`form_heading` text,\n\t`form_description` text,\n\t`form_button_label` text,\n\t`final_heading` text,\n\t`final_description` text,\n\t`final_button_label` text,\n\t`final_button_url` text,\n\t`block_name` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_contacts_hub_directions` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`title` text,\n\t`description` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home_blocks_contacts_hub`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_content` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_path` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`block_name` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_content_columns` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`size` text DEFAULT 'oneThird',\n\t`rich_text` text,\n\t`enable_link` integer,\n\t`link_type` text DEFAULT 'reference',\n\t`link_new_tab` integer,\n\t`link_url` text,\n\t`link_label` text,\n\t`link_appearance` text DEFAULT 'default',\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home_blocks_content`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_cta` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_path` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`rich_text` text,\n\t`block_name` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_cta_links` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`link_type` text DEFAULT 'reference',\n\t`link_new_tab` integer,\n\t`link_url` text,\n\t`link_label` text,\n\t`link_appearance` text DEFAULT 'default',\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home_blocks_cta`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_form_block` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_path` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`form_id` integer,\n\t`enable_intro` integer,\n\t`intro_content` text,\n\t`block_name` text,\n\tFOREIGN KEY (`form_id`) REFERENCES `forms`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_home_b2_b` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_path` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`eyebrow` text DEFAULT 'B2B / ГОСЗАКУПКИ / ПАРТНЕРСТВО',\n\t`title` text DEFAULT 'Поставки под проект, закупку и дилерские задачи',\n\t`description` text DEFAULT 'Помогаем пройти путь от запроса до поставки: уточняем задачу, подбираем оборудование, готовим коммерческое предложение и сопровождаем закупку.',\n\t`button_label` text DEFAULT 'Обсудить задачу и получить КП',\n\t`button_url` text DEFAULT '/kontakty',\n\t`block_name` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_home_b2_b_points` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`title` text,\n\t`description` text,\n\t`icon` text DEFAULT 'tender',\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home_blocks_home_b2_b`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_media_block` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_path` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`media_id` integer,\n\t`block_name` text,\n\tFOREIGN KEY (`media_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_service_center` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_path` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`hero_eyebrow` text,\n\t`hero_title` text,\n\t`hero_button_label` text,\n\t`hero_button_url` text,\n\t`hero_hero_image_id` integer,\n\t`service_request_heading` text,\n\t`service_request_description` text,\n\t`final_heading` text,\n\t`final_description` text,\n\t`final_button_label` text,\n\t`final_button_url` text,\n\t`block_name` text,\n\tFOREIGN KEY (`hero_hero_image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_service_center_cards` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`title` text,\n\t`description` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home_blocks_service_center`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_service_center_hero_paragraphs` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`text` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home_blocks_service_center`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_service_center_hero_visual_tags` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`label` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home_blocks_service_center`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_service_center_sections` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`heading` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home_blocks_service_center`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_service_center_sections_paragraphs` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`text` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home_blocks_service_center_sections`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_service_center_service_request_steps` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`label` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home_blocks_service_center`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_blocks_three_item_grid` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_path` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`block_name` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_hero_links` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`link_type` text DEFAULT 'reference',\n\t`link_new_tab` integer,\n\t`link_url` text,\n\t`link_label` text,\n\t`link_appearance` text DEFAULT 'default',\n\tFOREIGN KEY (`_parent_id`) REFERENCES `home`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `home_rels` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`order` integer,\n\t`parent_id` integer NOT NULL,\n\t`path` text NOT NULL,\n\t`pages_id` integer,\n\t`categories_id` integer,\n\t`products_id` integer,\n\tFOREIGN KEY (`parent_id`) REFERENCES `home`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`pages_id`) REFERENCES `pages`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`categories_id`) REFERENCES `categories`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`products_id`) REFERENCES `products`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `pages_blocks_home_b2_b` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_path` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`eyebrow` text DEFAULT 'B2B / ГОСЗАКУПКИ / ПАРТНЕРСТВО',\n\t`title` text DEFAULT 'Поставки под проект, закупку и дилерские задачи',\n\t`description` text DEFAULT 'Помогаем пройти путь от запроса до поставки: уточняем задачу, подбираем оборудование, готовим коммерческое предложение и сопровождаем закупку.',\n\t`button_label` text DEFAULT 'Обсудить задачу и получить КП',\n\t`button_url` text DEFAULT '/kontakty',\n\t`block_name` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `pages`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE TABLE IF NOT EXISTS `pages_blocks_home_b2_b_points` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`title` text,\n\t`description` text,\n\t`icon` text DEFAULT 'tender',\n\tFOREIGN KEY (`_parent_id`) REFERENCES `pages_blocks_home_b2_b`(`id`) ON UPDATE no action ON DELETE cascade\n);",
  "CREATE INDEX IF NOT EXISTS `_home_v_autosave_idx` ON `_home_v` (`autosave`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_about_company_facts_order_idx` ON `_home_v_blocks_about_company_facts` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_about_company_facts_parent_id_idx` ON `_home_v_blocks_about_company_facts` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_about_company_final_paragraphs_order_idx` ON `_home_v_blocks_about_company_final_paragraphs` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_about_company_final_paragraphs_parent_id_idx` ON `_home_v_blocks_about_company_final_paragraphs` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_about_company_hero_hero_hero_image_idx` ON `_home_v_blocks_about_company` (`hero_hero_image_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_about_company_hero_paragraphs_order_idx` ON `_home_v_blocks_about_company_hero_paragraphs` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_about_company_hero_paragraphs_parent_id_idx` ON `_home_v_blocks_about_company_hero_paragraphs` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_about_company_hero_visual_tags_order_idx` ON `_home_v_blocks_about_company_hero_visual_tags` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_about_company_hero_visual_tags_parent_id_idx` ON `_home_v_blocks_about_company_hero_visual_tags` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_about_company_order_idx` ON `_home_v_blocks_about_company` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_about_company_parent_id_idx` ON `_home_v_blocks_about_company` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_about_company_partners_paragraphs_order_idx` ON `_home_v_blocks_about_company_partners_paragraphs` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_about_company_partners_paragraphs_parent_id_idx` ON `_home_v_blocks_about_company_partners_paragraphs` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_about_company_partners_points_order_idx` ON `_home_v_blocks_about_company_partners_points` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_about_company_partners_points_parent_id_idx` ON `_home_v_blocks_about_company_partners_points` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_about_company_path_idx` ON `_home_v_blocks_about_company` (`_path`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_about_company_sections_order_idx` ON `_home_v_blocks_about_company_sections` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_about_company_sections_paragraphs_order_idx` ON `_home_v_blocks_about_company_sections_paragraphs` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_about_company_sections_paragraphs_parent_id_idx` ON `_home_v_blocks_about_company_sections_paragraphs` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_about_company_sections_parent_id_idx` ON `_home_v_blocks_about_company_sections` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_archive_order_idx` ON `_home_v_blocks_archive` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_archive_parent_id_idx` ON `_home_v_blocks_archive` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_archive_path_idx` ON `_home_v_blocks_archive` (`_path`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_banner_order_idx` ON `_home_v_blocks_banner` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_banner_parent_id_idx` ON `_home_v_blocks_banner` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_banner_path_idx` ON `_home_v_blocks_banner` (`_path`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_carousel_order_idx` ON `_home_v_blocks_carousel` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_carousel_parent_id_idx` ON `_home_v_blocks_carousel` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_carousel_path_idx` ON `_home_v_blocks_carousel` (`_path`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_contacts_hub_directions_order_idx` ON `_home_v_blocks_contacts_hub_directions` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_contacts_hub_directions_parent_id_idx` ON `_home_v_blocks_contacts_hub_directions` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_contacts_hub_order_idx` ON `_home_v_blocks_contacts_hub` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_contacts_hub_parent_id_idx` ON `_home_v_blocks_contacts_hub` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_contacts_hub_path_idx` ON `_home_v_blocks_contacts_hub` (`_path`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_content_columns_order_idx` ON `_home_v_blocks_content_columns` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_content_columns_parent_id_idx` ON `_home_v_blocks_content_columns` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_content_order_idx` ON `_home_v_blocks_content` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_content_parent_id_idx` ON `_home_v_blocks_content` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_content_path_idx` ON `_home_v_blocks_content` (`_path`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_cta_links_order_idx` ON `_home_v_blocks_cta_links` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_cta_links_parent_id_idx` ON `_home_v_blocks_cta_links` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_cta_order_idx` ON `_home_v_blocks_cta` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_cta_parent_id_idx` ON `_home_v_blocks_cta` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_cta_path_idx` ON `_home_v_blocks_cta` (`_path`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_form_block_form_idx` ON `_home_v_blocks_form_block` (`form_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_form_block_order_idx` ON `_home_v_blocks_form_block` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_form_block_parent_id_idx` ON `_home_v_blocks_form_block` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_form_block_path_idx` ON `_home_v_blocks_form_block` (`_path`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_home_b2_b_order_idx` ON `_home_v_blocks_home_b2_b` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_home_b2_b_parent_id_idx` ON `_home_v_blocks_home_b2_b` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_home_b2_b_path_idx` ON `_home_v_blocks_home_b2_b` (`_path`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_home_b2_b_points_order_idx` ON `_home_v_blocks_home_b2_b_points` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_home_b2_b_points_parent_id_idx` ON `_home_v_blocks_home_b2_b_points` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_media_block_media_idx` ON `_home_v_blocks_media_block` (`media_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_media_block_order_idx` ON `_home_v_blocks_media_block` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_media_block_parent_id_idx` ON `_home_v_blocks_media_block` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_media_block_path_idx` ON `_home_v_blocks_media_block` (`_path`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_service_center_cards_order_idx` ON `_home_v_blocks_service_center_cards` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_service_center_cards_parent_id_idx` ON `_home_v_blocks_service_center_cards` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_service_center_hero_hero_hero_image_idx` ON `_home_v_blocks_service_center` (`hero_hero_image_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_service_center_hero_paragraphs_order_idx` ON `_home_v_blocks_service_center_hero_paragraphs` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_service_center_hero_paragraphs_parent_id_idx` ON `_home_v_blocks_service_center_hero_paragraphs` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_service_center_hero_visual_tags_order_idx` ON `_home_v_blocks_service_center_hero_visual_tags` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_service_center_hero_visual_tags_parent_id_idx` ON `_home_v_blocks_service_center_hero_visual_tags` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_service_center_order_idx` ON `_home_v_blocks_service_center` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_service_center_parent_id_idx` ON `_home_v_blocks_service_center` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_service_center_path_idx` ON `_home_v_blocks_service_center` (`_path`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_service_center_sections_order_idx` ON `_home_v_blocks_service_center_sections` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_service_center_sections_paragraphs_order_idx` ON `_home_v_blocks_service_center_sections_paragraphs` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_service_center_sections_paragraphs_parent_id_idx` ON `_home_v_blocks_service_center_sections_paragraphs` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_service_center_sections_parent_id_idx` ON `_home_v_blocks_service_center_sections` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_service_center_service_request_steps_order_idx` ON `_home_v_blocks_service_center_service_request_steps` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_service_center_service_request_steps_parent_id_idx` ON `_home_v_blocks_service_center_service_request_steps` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_three_item_grid_order_idx` ON `_home_v_blocks_three_item_grid` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_three_item_grid_parent_id_idx` ON `_home_v_blocks_three_item_grid` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_blocks_three_item_grid_path_idx` ON `_home_v_blocks_three_item_grid` (`_path`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_created_at_idx` ON `_home_v` (`created_at`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_latest_idx` ON `_home_v` (`latest`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_rels_categories_id_idx` ON `_home_v_rels` (`categories_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_rels_order_idx` ON `_home_v_rels` (`order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_rels_pages_id_idx` ON `_home_v_rels` (`pages_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_rels_parent_idx` ON `_home_v_rels` (`parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_rels_path_idx` ON `_home_v_rels` (`path`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_rels_products_id_idx` ON `_home_v_rels` (`products_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_updated_at_idx` ON `_home_v` (`updated_at`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_version_hero_links_order_idx` ON `_home_v_version_hero_links` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_version_hero_links_parent_id_idx` ON `_home_v_version_hero_links` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_version_hero_version_hero_media_idx` ON `_home_v` (`version_hero_media_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_version_meta_version_meta_image_idx` ON `_home_v` (`version_meta_image_id`);",
  "CREATE INDEX IF NOT EXISTS `_home_v_version_version__status_idx` ON `_home_v` (`version__status`);",
  "CREATE INDEX IF NOT EXISTS `home__status_idx` ON `home` (`_status`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_about_company_facts_order_idx` ON `home_blocks_about_company_facts` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_about_company_facts_parent_id_idx` ON `home_blocks_about_company_facts` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_about_company_final_paragraphs_order_idx` ON `home_blocks_about_company_final_paragraphs` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_about_company_final_paragraphs_parent_id_idx` ON `home_blocks_about_company_final_paragraphs` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_about_company_hero_hero_hero_image_idx` ON `home_blocks_about_company` (`hero_hero_image_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_about_company_hero_paragraphs_order_idx` ON `home_blocks_about_company_hero_paragraphs` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_about_company_hero_paragraphs_parent_id_idx` ON `home_blocks_about_company_hero_paragraphs` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_about_company_hero_visual_tags_order_idx` ON `home_blocks_about_company_hero_visual_tags` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_about_company_hero_visual_tags_parent_id_idx` ON `home_blocks_about_company_hero_visual_tags` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_about_company_order_idx` ON `home_blocks_about_company` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_about_company_parent_id_idx` ON `home_blocks_about_company` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_about_company_partners_paragraphs_order_idx` ON `home_blocks_about_company_partners_paragraphs` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_about_company_partners_paragraphs_parent_id_idx` ON `home_blocks_about_company_partners_paragraphs` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_about_company_partners_points_order_idx` ON `home_blocks_about_company_partners_points` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_about_company_partners_points_parent_id_idx` ON `home_blocks_about_company_partners_points` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_about_company_path_idx` ON `home_blocks_about_company` (`_path`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_about_company_sections_order_idx` ON `home_blocks_about_company_sections` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_about_company_sections_paragraphs_order_idx` ON `home_blocks_about_company_sections_paragraphs` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_about_company_sections_paragraphs_parent_id_idx` ON `home_blocks_about_company_sections_paragraphs` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_about_company_sections_parent_id_idx` ON `home_blocks_about_company_sections` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_archive_order_idx` ON `home_blocks_archive` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_archive_parent_id_idx` ON `home_blocks_archive` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_archive_path_idx` ON `home_blocks_archive` (`_path`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_banner_order_idx` ON `home_blocks_banner` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_banner_parent_id_idx` ON `home_blocks_banner` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_banner_path_idx` ON `home_blocks_banner` (`_path`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_carousel_order_idx` ON `home_blocks_carousel` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_carousel_parent_id_idx` ON `home_blocks_carousel` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_carousel_path_idx` ON `home_blocks_carousel` (`_path`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_contacts_hub_directions_order_idx` ON `home_blocks_contacts_hub_directions` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_contacts_hub_directions_parent_id_idx` ON `home_blocks_contacts_hub_directions` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_contacts_hub_order_idx` ON `home_blocks_contacts_hub` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_contacts_hub_parent_id_idx` ON `home_blocks_contacts_hub` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_contacts_hub_path_idx` ON `home_blocks_contacts_hub` (`_path`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_content_columns_order_idx` ON `home_blocks_content_columns` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_content_columns_parent_id_idx` ON `home_blocks_content_columns` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_content_order_idx` ON `home_blocks_content` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_content_parent_id_idx` ON `home_blocks_content` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_content_path_idx` ON `home_blocks_content` (`_path`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_cta_links_order_idx` ON `home_blocks_cta_links` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_cta_links_parent_id_idx` ON `home_blocks_cta_links` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_cta_order_idx` ON `home_blocks_cta` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_cta_parent_id_idx` ON `home_blocks_cta` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_cta_path_idx` ON `home_blocks_cta` (`_path`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_form_block_form_idx` ON `home_blocks_form_block` (`form_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_form_block_order_idx` ON `home_blocks_form_block` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_form_block_parent_id_idx` ON `home_blocks_form_block` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_form_block_path_idx` ON `home_blocks_form_block` (`_path`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_home_b2_b_order_idx` ON `home_blocks_home_b2_b` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_home_b2_b_parent_id_idx` ON `home_blocks_home_b2_b` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_home_b2_b_path_idx` ON `home_blocks_home_b2_b` (`_path`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_home_b2_b_points_order_idx` ON `home_blocks_home_b2_b_points` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_home_b2_b_points_parent_id_idx` ON `home_blocks_home_b2_b_points` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_media_block_media_idx` ON `home_blocks_media_block` (`media_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_media_block_order_idx` ON `home_blocks_media_block` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_media_block_parent_id_idx` ON `home_blocks_media_block` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_media_block_path_idx` ON `home_blocks_media_block` (`_path`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_service_center_cards_order_idx` ON `home_blocks_service_center_cards` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_service_center_cards_parent_id_idx` ON `home_blocks_service_center_cards` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_service_center_hero_hero_hero_image_idx` ON `home_blocks_service_center` (`hero_hero_image_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_service_center_hero_paragraphs_order_idx` ON `home_blocks_service_center_hero_paragraphs` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_service_center_hero_paragraphs_parent_id_idx` ON `home_blocks_service_center_hero_paragraphs` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_service_center_hero_visual_tags_order_idx` ON `home_blocks_service_center_hero_visual_tags` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_service_center_hero_visual_tags_parent_id_idx` ON `home_blocks_service_center_hero_visual_tags` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_service_center_order_idx` ON `home_blocks_service_center` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_service_center_parent_id_idx` ON `home_blocks_service_center` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_service_center_path_idx` ON `home_blocks_service_center` (`_path`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_service_center_sections_order_idx` ON `home_blocks_service_center_sections` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_service_center_sections_paragraphs_order_idx` ON `home_blocks_service_center_sections_paragraphs` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_service_center_sections_paragraphs_parent_id_idx` ON `home_blocks_service_center_sections_paragraphs` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_service_center_sections_parent_id_idx` ON `home_blocks_service_center_sections` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_service_center_service_request_steps_order_idx` ON `home_blocks_service_center_service_request_steps` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_service_center_service_request_steps_parent_id_idx` ON `home_blocks_service_center_service_request_steps` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_three_item_grid_order_idx` ON `home_blocks_three_item_grid` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_three_item_grid_parent_id_idx` ON `home_blocks_three_item_grid` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_blocks_three_item_grid_path_idx` ON `home_blocks_three_item_grid` (`_path`);",
  "CREATE INDEX IF NOT EXISTS `home_hero_hero_media_idx` ON `home` (`hero_media_id`);",
  "CREATE INDEX IF NOT EXISTS `home_hero_links_order_idx` ON `home_hero_links` (`_order`);",
  "CREATE INDEX IF NOT EXISTS `home_hero_links_parent_id_idx` ON `home_hero_links` (`_parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_meta_meta_image_idx` ON `home` (`meta_image_id`);",
  "CREATE INDEX IF NOT EXISTS `home_rels_categories_id_idx` ON `home_rels` (`categories_id`);",
  "CREATE INDEX IF NOT EXISTS `home_rels_order_idx` ON `home_rels` (`order`);",
  "CREATE INDEX IF NOT EXISTS `home_rels_pages_id_idx` ON `home_rels` (`pages_id`);",
  "CREATE INDEX IF NOT EXISTS `home_rels_parent_idx` ON `home_rels` (`parent_id`);",
  "CREATE INDEX IF NOT EXISTS `home_rels_path_idx` ON `home_rels` (`path`);",
  "CREATE INDEX IF NOT EXISTS `home_rels_products_id_idx` ON `home_rels` (`products_id`);"
] as const

const downStatements = [
  "DROP INDEX IF EXISTS `home_rels_products_id_idx`;",
  "DROP INDEX IF EXISTS `home_rels_path_idx`;",
  "DROP INDEX IF EXISTS `home_rels_parent_idx`;",
  "DROP INDEX IF EXISTS `home_rels_pages_id_idx`;",
  "DROP INDEX IF EXISTS `home_rels_order_idx`;",
  "DROP INDEX IF EXISTS `home_rels_categories_id_idx`;",
  "DROP INDEX IF EXISTS `home_meta_meta_image_idx`;",
  "DROP INDEX IF EXISTS `home_hero_links_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_hero_links_order_idx`;",
  "DROP INDEX IF EXISTS `home_hero_hero_media_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_three_item_grid_path_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_three_item_grid_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_three_item_grid_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_service_center_service_request_steps_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_service_center_service_request_steps_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_service_center_sections_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_service_center_sections_paragraphs_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_service_center_sections_paragraphs_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_service_center_sections_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_service_center_path_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_service_center_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_service_center_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_service_center_hero_visual_tags_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_service_center_hero_visual_tags_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_service_center_hero_paragraphs_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_service_center_hero_paragraphs_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_service_center_hero_hero_hero_image_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_service_center_cards_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_service_center_cards_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_media_block_path_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_media_block_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_media_block_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_media_block_media_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_home_b2_b_points_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_home_b2_b_points_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_home_b2_b_path_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_home_b2_b_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_home_b2_b_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_form_block_path_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_form_block_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_form_block_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_form_block_form_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_cta_path_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_cta_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_cta_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_cta_links_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_cta_links_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_content_path_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_content_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_content_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_content_columns_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_content_columns_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_contacts_hub_path_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_contacts_hub_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_contacts_hub_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_contacts_hub_directions_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_contacts_hub_directions_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_carousel_path_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_carousel_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_carousel_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_banner_path_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_banner_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_banner_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_archive_path_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_archive_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_archive_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_about_company_sections_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_about_company_sections_paragraphs_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_about_company_sections_paragraphs_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_about_company_sections_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_about_company_path_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_about_company_partners_points_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_about_company_partners_points_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_about_company_partners_paragraphs_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_about_company_partners_paragraphs_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_about_company_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_about_company_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_about_company_hero_visual_tags_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_about_company_hero_visual_tags_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_about_company_hero_paragraphs_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_about_company_hero_paragraphs_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_about_company_hero_hero_hero_image_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_about_company_final_paragraphs_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_about_company_final_paragraphs_order_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_about_company_facts_parent_id_idx`;",
  "DROP INDEX IF EXISTS `home_blocks_about_company_facts_order_idx`;",
  "DROP INDEX IF EXISTS `home__status_idx`;",
  "DROP INDEX IF EXISTS `_home_v_version_version__status_idx`;",
  "DROP INDEX IF EXISTS `_home_v_version_meta_version_meta_image_idx`;",
  "DROP INDEX IF EXISTS `_home_v_version_hero_version_hero_media_idx`;",
  "DROP INDEX IF EXISTS `_home_v_version_hero_links_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_version_hero_links_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_updated_at_idx`;",
  "DROP INDEX IF EXISTS `_home_v_rels_products_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_rels_path_idx`;",
  "DROP INDEX IF EXISTS `_home_v_rels_parent_idx`;",
  "DROP INDEX IF EXISTS `_home_v_rels_pages_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_rels_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_rels_categories_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_latest_idx`;",
  "DROP INDEX IF EXISTS `_home_v_created_at_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_three_item_grid_path_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_three_item_grid_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_three_item_grid_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_service_center_service_request_steps_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_service_center_service_request_steps_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_service_center_sections_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_service_center_sections_paragraphs_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_service_center_sections_paragraphs_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_service_center_sections_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_service_center_path_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_service_center_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_service_center_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_service_center_hero_visual_tags_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_service_center_hero_visual_tags_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_service_center_hero_paragraphs_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_service_center_hero_paragraphs_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_service_center_hero_hero_hero_image_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_service_center_cards_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_service_center_cards_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_media_block_path_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_media_block_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_media_block_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_media_block_media_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_home_b2_b_points_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_home_b2_b_points_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_home_b2_b_path_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_home_b2_b_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_home_b2_b_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_form_block_path_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_form_block_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_form_block_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_form_block_form_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_cta_path_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_cta_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_cta_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_cta_links_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_cta_links_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_content_path_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_content_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_content_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_content_columns_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_content_columns_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_contacts_hub_path_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_contacts_hub_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_contacts_hub_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_contacts_hub_directions_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_contacts_hub_directions_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_carousel_path_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_carousel_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_carousel_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_banner_path_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_banner_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_banner_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_archive_path_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_archive_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_archive_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_about_company_sections_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_about_company_sections_paragraphs_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_about_company_sections_paragraphs_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_about_company_sections_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_about_company_path_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_about_company_partners_points_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_about_company_partners_points_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_about_company_partners_paragraphs_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_about_company_partners_paragraphs_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_about_company_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_about_company_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_about_company_hero_visual_tags_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_about_company_hero_visual_tags_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_about_company_hero_paragraphs_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_about_company_hero_paragraphs_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_about_company_hero_hero_hero_image_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_about_company_final_paragraphs_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_about_company_final_paragraphs_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_about_company_facts_parent_id_idx`;",
  "DROP INDEX IF EXISTS `_home_v_blocks_about_company_facts_order_idx`;",
  "DROP INDEX IF EXISTS `_home_v_autosave_idx`;",
  "DROP TABLE IF EXISTS `pages_blocks_home_b2_b_points`;",
  "DROP TABLE IF EXISTS `pages_blocks_home_b2_b`;",
  "DROP TABLE IF EXISTS `home_rels`;",
  "DROP TABLE IF EXISTS `home_hero_links`;",
  "DROP TABLE IF EXISTS `home_blocks_three_item_grid`;",
  "DROP TABLE IF EXISTS `home_blocks_service_center_service_request_steps`;",
  "DROP TABLE IF EXISTS `home_blocks_service_center_sections_paragraphs`;",
  "DROP TABLE IF EXISTS `home_blocks_service_center_sections`;",
  "DROP TABLE IF EXISTS `home_blocks_service_center_hero_visual_tags`;",
  "DROP TABLE IF EXISTS `home_blocks_service_center_hero_paragraphs`;",
  "DROP TABLE IF EXISTS `home_blocks_service_center_cards`;",
  "DROP TABLE IF EXISTS `home_blocks_service_center`;",
  "DROP TABLE IF EXISTS `home_blocks_media_block`;",
  "DROP TABLE IF EXISTS `home_blocks_home_b2_b_points`;",
  "DROP TABLE IF EXISTS `home_blocks_home_b2_b`;",
  "DROP TABLE IF EXISTS `home_blocks_form_block`;",
  "DROP TABLE IF EXISTS `home_blocks_cta_links`;",
  "DROP TABLE IF EXISTS `home_blocks_cta`;",
  "DROP TABLE IF EXISTS `home_blocks_content_columns`;",
  "DROP TABLE IF EXISTS `home_blocks_content`;",
  "DROP TABLE IF EXISTS `home_blocks_contacts_hub_directions`;",
  "DROP TABLE IF EXISTS `home_blocks_contacts_hub`;",
  "DROP TABLE IF EXISTS `home_blocks_carousel`;",
  "DROP TABLE IF EXISTS `home_blocks_banner`;",
  "DROP TABLE IF EXISTS `home_blocks_archive`;",
  "DROP TABLE IF EXISTS `home_blocks_about_company_sections_paragraphs`;",
  "DROP TABLE IF EXISTS `home_blocks_about_company_sections`;",
  "DROP TABLE IF EXISTS `home_blocks_about_company_partners_points`;",
  "DROP TABLE IF EXISTS `home_blocks_about_company_partners_paragraphs`;",
  "DROP TABLE IF EXISTS `home_blocks_about_company_hero_visual_tags`;",
  "DROP TABLE IF EXISTS `home_blocks_about_company_hero_paragraphs`;",
  "DROP TABLE IF EXISTS `home_blocks_about_company_final_paragraphs`;",
  "DROP TABLE IF EXISTS `home_blocks_about_company_facts`;",
  "DROP TABLE IF EXISTS `home_blocks_about_company`;",
  "DROP TABLE IF EXISTS `home`;",
  "DROP TABLE IF EXISTS `_pages_v_blocks_home_b2_b_points`;",
  "DROP TABLE IF EXISTS `_pages_v_blocks_home_b2_b`;",
  "DROP TABLE IF EXISTS `_home_v_version_hero_links`;",
  "DROP TABLE IF EXISTS `_home_v_rels`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_three_item_grid`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_service_center_service_request_steps`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_service_center_sections_paragraphs`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_service_center_sections`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_service_center_hero_visual_tags`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_service_center_hero_paragraphs`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_service_center_cards`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_service_center`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_media_block`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_home_b2_b_points`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_home_b2_b`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_form_block`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_cta_links`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_cta`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_content_columns`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_content`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_contacts_hub_directions`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_contacts_hub`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_carousel`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_banner`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_archive`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_about_company_sections_paragraphs`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_about_company_sections`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_about_company_partners_points`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_about_company_partners_paragraphs`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_about_company_hero_visual_tags`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_about_company_hero_paragraphs`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_about_company_final_paragraphs`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_about_company_facts`;",
  "DROP TABLE IF EXISTS `_home_v_blocks_about_company`;",
  "DROP TABLE IF EXISTS `_home_v`;"
] as const

export async function up({ db }: MigrateUpArgs): Promise<void> {
  for (const statement of upStatements) {
    await db.run(sql.raw(statement))
  }
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  for (const statement of downStatements) {
    await db.run(sql.raw(statement))
  }
}
